//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hackaton.Models
{
    using System;
    
    public partial class ConductorCercano
    {
        public string Nombre { get; set; }
        public string Apellidos { get; set; }
        public string Telefono { get; set; }
        public string Email { get; set; }
        public System.TimeSpan HoraSalida { get; set; }
        public System.TimeSpan HoraRegreso { get; set; }
        public string Origen { get; set; }
        public double DistanciaOrigen { get; set; }
        public string Destino { get; set; }
        public double DistanciaDestino { get; set; }
    }
}
