//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hackaton.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ruta
    {
        public Ruta()
        {
            this.Paradas = new HashSet<Parada>();
        }
    
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string Origen_Nombre { get; set; }
        public System.Data.Spatial.DbGeography Origen { get; set; }
        public string Destino_Nombre { get; set; }
        public System.Data.Spatial.DbGeography Destino { get; set; }
        public Nullable<int> FrecuenciaMin { get; set; }
    
        public virtual ICollection<Parada> Paradas { get; set; }
    }
}
